import { Product, Category, Order, Review, NotificationItem } from './types';

export const INITIAL_CATEGORIES: Category[] = [
  {
    id: 'smartwatch',
    name: 'ساعت هوشمند',
    slug: 'smartwatch',
    image: '/assets/products/smartwatch-x1.webp',
    itemCount: 18,
  },
  {
    id: 'headphones',
    name: 'هدفون و هندزفری',
    slug: 'headphones',
    image: '/assets/products/headphone-pro.webp',
    itemCount: 24,
  },
  {
    id: 'perfume',
    name: 'عطر و ادکلن',
    slug: 'perfume',
    image: '/assets/products/perfume-lux.webp',
    itemCount: 32,
  },
  {
    id: 'accessories',
    name: 'اکسسوری',
    slug: 'accessories',
    image: '/assets/products/leather-wallet.webp',
    itemCount: 45,
  },
];

export const INITIAL_PRODUCTS: Product[] = [
  {
    id: 'headphone-pro',
    title: 'هدفون بی‌سیم پریمیوم پرو',
    slug: 'wireless-headphone-premium-pro',
    category: 'headphones',
    price: 3980000,
    originalPrice: 4500000,
    discountPercent: 11,
    rating: 4.8,
    reviewsCount: 124,
    image: '/assets/products/screen-removebg-preview.webp',
    gallery: ['/assets/products/screen-removebg-preview.webp'], 
    shortDescription: 'تجربه صدایی بی‌نظیر با تکنولوژی حذف نویز هوشمند و طراحی ارگونومیک برای استفاده طولانی مدت.',
    description: 'هدست بی‌سیم حرفه‌ای با حذف نویز فعال هیبریدی، درایورهای ۴۰ میلی‌متری تیتانیومی و تا ۷۰ ساعت شارژدهی مداوم. این هدفون با بدنه‌ای از جنس آلومینیوم مات سبک و بالشتک‌های چرم طبیعی فوق‌العاده نرم، ترکیبی از نهایت زیبایی مدرن و نهایت راحتی آکوستیک را به ارمغان می‌آورد.',
    colors: [
      { name: 'مشکی مات', hex: '#1a1a1a', inStock: true },
      { name: 'نقره‌ای کلاسیک', hex: '#e3e4e5', inStock: true },
      { name: 'بژ طلایی', hex: '#f4ebd0', inStock: true },
    ],
    stock: 3,
    sku: 'PRO-W',
    isNew: true,
    isFeatured: true,
    specs: [
      { label: 'نوع اتصال', value: 'بی‌سیم (بلوتوث ۵.۳) و باسیم (کابل ۳.۵ میلی‌متری)' },
      { label: 'عمر باتری', value: 'تا ۷۰ ساعت با خاموش بودن ANC / ۵۰ ساعت با ANC روشن' },
      { label: 'زمان شارژ کامل', value: '۱.۵ ساعت از طریق درگاه تایپ C' },
      { label: 'درایور صوتی', value: '۴۰ میلی‌متری سفارشی تیتانیوم' },
      { label: 'میکروفون', value: '۴ میکروفون پیشرفته با حذف اکو و نویز محیط' },
      { label: 'وزن', value: '۲۴۵ گرم' },
    ],
    features: [
      'حذف نویز فعال هوشمند (Adaptive ANC)',
      'پشتیبانی از صدای فراگیر فضایی ۳۶۰ درجه',
      'قابلیت اتصال همزمان به دو دستگاه (Multipoint)',
      'بالشتک‌های حافظه‌دار ارگونومیک با چرم طبیعی نفوذپذیر',
    ],
  },
  {
    id: 'smartwatch-x1',
    title: 'ساعت هوشمند مدل X1',
    slug: 'smartwatch-x1',
    category: 'smartwatch',
    price: 3980000,
    originalPrice: 4200000,
    discountPercent: 5,
    rating: 4.8,
    reviewsCount: 96,
    image: '/assets/products/smartwatch-x1.webp',
    gallery: ['/assets/products/smartwatch-x1.webp'],
    shortDescription: 'ساعت هوشمند شیک با نمایشگر AMOLED باکیفیت و سنجش مداوم ضربان قلب و اکسیژن خون.',
    description: 'ساعت هوشمند مدل X1 با بدنه استیل ضد زنگ و شیشه مقاوم یاقوت کبود، پایش جامع سلامتی و بیش از ۱۰۰ حالت ورزشی اختصاصی را در کنار اعلانات هوشمند فارسی ارائه می‌دهد.',
    colors: [
      { name: 'مشکی مات', hex: '#1a1a1a', inStock: true },
      { name: 'نقره‌ای', hex: '#d1d5db', inStock: true },
    ],
    stock: 14,
    sku: 'WATCH-X1',
    isNew: true,
    isFeatured: true,
    specs: [
      { label: 'صفحه نمایش', value: '۱.۴۳ اینچ AMOLED با رزولوشن ۴۶۶×۴۶۶' },
      { label: 'باتری', value: 'تا ۱۴ روز استفاده معمولی' },
      { label: 'مقاومت در برابر آب', value: 'استاندارد ۵ATM تا عمق ۵۰ متر' },
      { label: 'سازگاری', value: 'اندروید و iOS' },
    ],
    features: ['سنجش ضربان قلب و SpO2', 'پشتیبانی کامل از زبان فارسی', 'مکالمه بلوتوثی شفاف'],
  },
  {
    id: 'earbuds-pro',
    title: 'ایرفون بی‌سیم پرو',
    slug: 'earphone-wireless-pro',
    category: 'headphones',
    price: 2450000,
    originalPrice: 2800000,
    discountPercent: 12,
    rating: 4.5,
    reviewsCount: 88,
    image: '/assets/products/earbuds-pro.webp',
    gallery: ['/assets/products/earbuds-pro.webp'],
    shortDescription: 'هندزفری بلوتوثی توگوشی با کیس شارژ جمع‌وجور، بیس عمیق و تفکیک صدای کریستالی.',
    description: 'ایرفون پرو با طراحی سبک و ضد تعریق، تا ۳۲ ساعت موسیقی با کیس شارژ، و میکروفون دوگانه با سیستم هوشمند کاهش نویز باد.',
    colors: [
      { name: 'مشکی', hex: '#1a1a1a', inStock: true },
      { name: 'سفید صدفی', hex: '#ffffff', inStock: true },
    ],
    stock: 22,
    sku: 'EAR-PRO',
    isNew: false,
    isFeatured: true,
    specs: [
      { label: 'نسخه بلوتوث', value: 'Bluetooth 5.3' },
      { label: 'شارژدهی', value: '۸ ساعت مداوم (۳۲ ساعت با کیس)' },
      { label: 'حالت گیمینگ', value: 'تأخیر بسیار کم ۴۵ میلی‌ثانیه' },
    ],
    features: ['کنترل لمسی هوشمند', 'مقاوم در برابر پاشش آب IPX5', 'پشتیبانی از کدک AAC و SBC'],
  },
  {
    id: 'minimal-lamp',
    title: 'آباژور مدرن مینیمال',
    slug: 'modern-minimalist-lamp',
    category: 'accessories',
    price: 1850000,
    originalPrice: 2100000,
    discountPercent: 12,
    rating: 4.9,
    reviewsCount: 53,
    image: '/assets/products/minimal-lamp.webp',
    gallery: ['/assets/products/minimal-lamp.webp'],
    shortDescription: 'چراغ رومیزی با نور گرم تنظیم‌پذیر و طراحی ارگانیک ابری الهام‌گرفته از مینیمالیسم ژاپنی.',
    description: 'ساخته شده از پایه‌ فولادی مات و حباب سیلیکونی انتشار نور یکنواخت، بدون سوسو زدن، مناسب برای میز کار و اتاق خواب مدرن.',
    colors: [
      { name: 'سفید عاجی', hex: '#fdfbf7', inStock: true },
      { name: 'خاکستری روشن', hex: '#e5e7eb', inStock: true },
    ],
    stock: 9,
    sku: 'LAMP-MIN',
    isNew: true,
    isFeatured: true,
    specs: [
      { label: 'منبع نور', value: 'LED با عمر بیش از ۵۰,۰۰۰ ساعت' },
      { label: 'دمای نور', value: 'سه حالت: آفتابی، مهتابی، طبیعی (۳۰۰۰K - ۵۰۰۰K)' },
      { label: 'کنترل', value: 'دیمر لمسی بدون پله' },
    ],
    features: ['صرفه‌جویی انرژی رده A++', 'بدون خستگی چشم', 'پایه ضد لغزش'],
  },
  {
    id: 'leather-wallet',
    title: 'کیف پول چرم طبیعی',
    slug: 'genuine-leather-wallet',
    category: 'accessories',
    price: 850000,
    originalPrice: 950000,
    discountPercent: 10,
    rating: 4.7,
    reviewsCount: 71,
    image: '/assets/products/leather-wallet.webp',
    gallery: ['/assets/products/leather-wallet.webp'],
    shortDescription: 'کیف پول جیبی دوخته شده از چرم صد در صد طبیعی گاوی با پرداخت دستی و محافظ RFID.',
    description: 'دست‌دوز با نخ موم‌زده ایتالیایی، دارای ۸ جایگاه کارت بانکی، دو محفظه اسکناس و بخش امن زیپ‌دار برای سکه یا اقلام کوچک.',
    colors: [
      { name: 'قهوه‌ای عسلی', hex: '#b45309', inStock: true },
      { name: 'مشکی کلاسیک', hex: '#18181b', inStock: true },
    ],
    stock: 19,
    sku: 'WAL-LTH',
    isNew: false,
    isFeatured: true,
    specs: [
      { label: 'جنس', value: 'چرم طبیعی فول گرین گاوی' },
      { label: 'ابعاد', value: '۱۱.۵ × ۹.۵ سانتی‌متر' },
      { label: 'تکنولوژی محافظ', value: 'RFID ضد سرقت اطلاعات کارت' },
    ],
    features: ['دوخت مستحکم دست‌دوز', 'بسته‌بندی هدیه شکیل چوبی', 'گارانتی اصالت ۲ ساله چرم'],
  },
  {
    id: 'perfume-lux',
    title: 'عطر مردانه لوکس',
    slug: 'luxury-men-perfume',
    category: 'perfume',
    price: 4200000,
    originalPrice: 4800000,
    discountPercent: 12,
    rating: 4.6,
    reviewsCount: 64,
    image: '/assets/products/perfume-lux.webp',
    gallery: ['/assets/products/perfume-lux.webp'],
    shortDescription: 'ادو پرفیوم با رایحه چوبی-معطر با ماندگاری فوق‌العاده و پخش بوی بالا.',
    description: 'ترکیبی شاهکار از نت‌های ترنج سیسیلی، فلفل سیاه، چوب سدر و کهربای خاکستری. تجسمی از شکوه و وقار مردانه برای مجالس رسمی.',
    colors: [
      { name: 'شیشه شفاف کریستالی', hex: '#f3f4f6', inStock: true },
    ],
    stock: 7,
    sku: 'PERF-LUX',
    isNew: true,
    isFeatured: true,
    specs: [
      { label: 'حجم', value: '۱۰۰ میلی‌لیتر' },
      { label: 'غلظت', value: 'ادو پرفیوم (Eau de Parfum)' },
      { label: 'کشور مبدأ', value: 'فرانسه' },
      { label: 'ماندگاری', value: 'بیش از ۲۴ ساعت' },
    ],
    features: ['شیشه کریستالی سنگین دست‌ساز', 'پخش بوی ماندگار در محیط', 'طبع گرم و تلخ شیک'],
  },
  {
    id: 'cologne-noir',
    title: 'ادکلن مردانه نویر',
    slug: 'men-cologne-noir',
    category: 'perfume',
    price: 3100000,
    originalPrice: 3500000,
    discountPercent: 11,
    rating: 4.8,
    reviewsCount: 112,
    image: '/assets/products/cologne-noir.webp',
    gallery: ['/assets/products/cologne-noir.webp'],
    shortDescription: 'رایحه دودی و چرمی اغواکننده با طبع گرم، مناسب فصول سرد سال و قرارهای ویژه.',
    description: 'ادکلن نویر با نوت‌های چرم دباغی‌شده، زعفران، یاسمن و هل سیاه، امضایی خاص برای کسانی است که همیشه در یادها می‌مانند.',
    colors: [
      { name: 'شیشه دودی کهربایی', hex: '#78350f', inStock: true },
    ],
    stock: 12,
    sku: 'PERF-NOIR',
    isNew: false,
    isFeatured: true,
    specs: [
      { label: 'حجم', value: '۱۰۰ میلی‌لیتر' },
      { label: 'گروه بویایی', value: 'چرمی چوبی معطر' },
      { label: 'فصل پیشنهادی', value: 'پاییز و زمستان' },
    ],
    features: ['رایحه منحصر‌به‌فرد خاص', 'طراحی شیشه مینیمال لوکس', 'ضمانت اصالت صد در صدی'],
  },
  {
    id: 'cologne-blue',
    title: 'ادکلن مردانه بلو',
    slug: 'men-cologne-blue',
    category: 'perfume',
    price: 1250000,
    originalPrice: 1500000,
    discountPercent: 17,
    rating: 4.6,
    reviewsCount: 45,
    image: '/assets/products/cologne-noir.webp',
    gallery: ['/assets/products/cologne-noir.webp'],
    shortDescription: 'رایحه خنک اقیانوسی و مرکباتی، انرژی‌بخش و شاداب برای روزهای گرم و فعالیت‌های روزمره.',
    description: 'ادکلن بلو با آکوردهای آبی، گریپ‌فروت، زنجبیل و چوب صندل، نسیمی از اقیانوس را به روز شما هدیه می‌دهد.',
    colors: [
      { name: 'آبی اقیانوسی', hex: '#1e3a8a', inStock: true },
    ],
    stock: 2,
    sku: 'COL-BL',
    isNew: false,
    isFeatured: true,
    specs: [
      { label: 'حجم', value: '۱۰۰ میلی‌لیتر' },
      { label: 'طبع', value: 'خنک و ملایم' },
      { label: 'ماندگاری', value: '۸ الی ۱۲ ساعت' },
    ],
    features: ['رایحه همه‌پسند خنک', 'مناسب مصرف روزانه و ورزش', 'قیمت اقتصادی'],
  },
];

export const INITIAL_ORDERS: Order[] = [
  {
    id: 'ord-8932',
    orderNumber: '#ORD-8932',
    customerName: 'علی رضایی',
    customerPhone: '۰۹۱۲۳۴۵۶۷۸۹',
    date: '۱۴۰۲/۰۸/۲۴',
    items: [
      {
        product: INITIAL_PRODUCTS[1], // Smartwatch X1
        quantity: 1,
        selectedColor: 'مشکی مات',
      },
    ],
    totalAmount: 3980000,
    discountAmount: 220000,
    shippingMethod: 'پست پیشتاز',
    shippingCost: 0,
    status: 'processing',
    address: {
      fullName: 'علی رضایی',
      phone: '۰۹۱۲۳۴۵۶۷۸۹',
      province: 'تهران',
      city: 'تهران',
      postalCode: '۱۹۸۷۶۵۴۳۲۱',
      street: 'خیابان ولیعصر، نرسیده به میدان ونک، برج نگین، طبقه ۵',
      notes: 'لطفاً قبل از تحویل تماس بگیرید.',
    },
    paymentMethod: 'درگاه پرداخت آنلاین سامان',
  },
  {
    id: 'ord-8931',
    orderNumber: '#ORD-8931',
    customerName: 'سارا محمدی',
    customerPhone: '۰۹۳۵۹۸۷۶۵۴۳',
    date: '۱۴۰۲/۰۸/۲۴',
    items: [
      {
        product: INITIAL_PRODUCTS[7], // Cologne Blue
        quantity: 1,
        selectedColor: 'آبی اقیانوسی',
      },
    ],
    totalAmount: 1250000,
    discountAmount: 250000,
    shippingMethod: 'پیک اختصاصی اکسپرس',
    shippingCost: 45000,
    status: 'shipped',
    address: {
      fullName: 'سارا محمدی',
      phone: '۰۹۳۵۹۸۷۶۵۴۳',
      province: 'تهران',
      city: 'تهران',
      postalCode: '۱۴۳۲۵۶۷۸۹۰',
      street: 'سعادت آباد، بلوار پاکنژاد، کوچه شبنم، پلاک ۱۲',
    },
    paymentMethod: 'درگاه پرداخت ملت',
  },
  {
    id: 'ord-8930',
    orderNumber: '#ORD-8930',
    customerName: 'امیرحسین کریمی',
    customerPhone: '۰۹۱۹۱۱۱۲۲۳۳',
    date: '۱۴۰۲/۰۸/۲۲',
    items: [
      {
        product: INITIAL_PRODUCTS[0], // Headphone Pro
        quantity: 1,
        selectedColor: 'مشکی مات',
      },
      {
        product: INITIAL_PRODUCTS[4], // Leather Wallet
        quantity: 1,
        selectedColor: 'قهوه‌ای عسلی',
      },
    ],
    totalAmount: 4830000,
    discountAmount: 620000,
    shippingMethod: 'پست پیشتاز',
    shippingCost: 0,
    status: 'delivered',
    address: {
      fullName: 'امیرحسین کریمی',
      phone: '۰۹۱۹۱۱۱۲۲۳۳',
      province: 'اصفهان',
      city: 'اصفهان',
      postalCode: '۸۱۷۳۹۲۴۶۸۰',
      street: 'خیابان چهارباغ بالا، مجتمع تجاری کوثر',
    },
    paymentMethod: 'درگاه پرداخت آنلاین',
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev-1',
    productId: 'headphone-pro',
    userName: 'کامران یوسفی',
    rating: 5,
    date: '۳ روز پیش',
    comment: 'کیفیت ساخت و متریال بی‌نظیره. قابلیت حذف نویز با بهترین هدفون‌های روز رقابت می‌کنه و صدای شفاف و بیس کنترل‌شده‌ای داره.',
  },
  {
    id: 'rev-2',
    productId: 'headphone-pro',
    userName: 'مهسا نوری',
    rating: 5,
    date: '۱ هفته پیش',
    comment: 'طراحی بسیار شیک و چشم‌نواز با بالشتک‌های فوق‌العاده راحت. بعد از ۶ ساعت کار مداوم اصلاً گوشم خسته نشد.',
  },
  {
    id: 'rev-3',
    productId: 'headphone-pro',
    userName: 'رضا افشار',
    rating: 4,
    date: '۲ هفته پیش',
    comment: 'شارژدهی باتری عالیه، واقعاً چندین روز بدون نیاز به شارژ کار کرد. ارسالش هم کمتر از ۲۴ ساعت طول کشید.',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'سفارش جدید ثبت شد',
    message: 'سفارش #ORD-8932 توسط علی رضایی با موفقیت ثبت شد.',
    date: '۱۰ دقیقه پیش',
    read: false,
    type: 'order',
  },
  {
    id: 'notif-2',
    title: 'هشدار موجودی کم',
    message: 'موجودی کالای «ادکلن مردانه بلو» به ۲ عدد رسیده است.',
    date: '۲ ساعت پیش',
    read: false,
    type: 'system',
  },
  {
    id: 'notif-3',
    title: 'جشنواره تخفیف پاییزه',
    message: 'کمپین تخفیف ویژه محصولات لوازم جانبی فعال شد.',
    date: 'دیروز',
    read: false,
    type: 'discount',
  },
];

// Helper to format numbers into Persian digits with commas
export function toPersianDigits(num: number | string): string {
  const persianDigits = ['۰', '۱', '۲', '۳', '۴', '۵', '۶', '۷', '۸', '۹'];
  return String(num).replace(/[0-9]/g, (w) => persianDigits[+w]);
}

export function formatPrice(price: number): string {
  const formattedWithCommas = price.toLocaleString('en-US');
  return toPersianDigits(formattedWithCommas);
}
